name: demo_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  fraction: ^5.0.2
  image_picker: ^1.1.0
  video_editor: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
